name: actions

on: 
    workflow_dispatch: 


jobs: 
    test-actions:
        name: test action
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run: ls
            - name: checkout repo
              uses: actions/checkout@v4.1.1
            - name: ls
              run: ls
            - name: Print to log
              id: print-to-log
              uses: actions/hello-world-javascript-action@main
              with:
                who-to-greet: "Zafin"
            - name: time
              run: echo "'Greeting time' ${{steps.print-to-log.outputs.time}}"
            - name: docker action
              uses: docker://hello-world:latest