name: artifacts


on:
    push

jobs:
    download-artifact:
        needs: upload-artifact
        name: download and run artifact
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/download-artifact@v4
              with:
                  name: my-artifact
            - name: Display structure of the downloaded artifact
              run: ls -R
            - run: cat myArtifacts.txt
    upload-artifact: 
        name: job to upload an artifact
        runs-on: ubuntu-latest
        steps:
            - run: docker info > myArtifacts.txt
            - uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: myArtifacts.txt