name: cache

on:
 workflow_dispatch: 

jobs:
    test-cache:
        name: job to test acche
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.1.1
        - uses: actions/cache@v3
          id: generateCache
          with: 
            path: ~/.cache/pip
            key: ${{runner.os}}-pip-${{hashFiles('**/first.txt')}}
            restore-keys: |
                ${{runner.os}}-pip-
        - run: pip install -r first.txt
        - name: confirm cache
          if: steps.generateCache.outputs.cache-hit == 'true'
          run: echo cache entry found!